### ISSUE TITLE
Migliorare la scheda staff

### ISSUE THREAD

**Issue by ncarandini** [DomusDotNet/domusdotnet.github.io#8]
Attualmente il layout della scheda di dettaglio dei chi siamo fa un po' pena, bisognerebbe sistemarla aggiungendo i dati social relativi alla persona, che sono già inseriti del "front matter" (lo spazio dedicato alle variabili, compreso tra i tre meno iniziali e quelli finali) delle nostre schede.

I file da modificare sono essenzialmente due:
- _layout/staff_member.html
- css/custom/layouts/staff-member.scss

**Comment by pythonyan** [comment]
Ho creato un mio branch  ed apportato delle modifiche, dategli un'occhiata (avevo una mezzoretta :-) ).
